version: "3.9"
services:
  pymagnum:
    image: python-pymagnum   # built from your Dockerfile
    container_name: pymagnum-bash
#    command: /bin/bash
#    stdin_open: true   # equivalent to -i
#    tty: true          # equivalent to -t
    restart: unless-stopped
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
        - 17223:17223

